package co.ke.tezza.loanapp.model;

import java.math.BigDecimal;
import java.util.Date;

import co.ke.tezza.loanapp.enums.ReferralrewardTypeEnum;
import co.ke.tezza.loanapp.enums.SettingCategoriesEnum;
import co.ke.tezza.loanapp.enums.SystemStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SystemSettingsConfig {
    private long id;

    private boolean oTPAllowedOnLogin;
    private boolean searchEnabled;
    private SettingCategoriesEnum settingCategory;

    private boolean referralBenefitsEnabled;
    private BigDecimal referralFlatBonusAmount;
    private BigDecimal referralFlatBonusInterestRate;
    private boolean referralBenefitIsOneTime;
    private ReferralrewardTypeEnum referralRewardType;

    private String platformName;
    private String platformPrimaryColor;

    private boolean notifyOnMatch;
    private boolean notifyOnMaturity;

    private boolean maintenanceModeEnabled;
    private String maintenanceMessage;

    private BigDecimal systemOwnerRate; 
    private boolean allowAutoOwnerBenefitAllocation;
    private boolean allowAutoSharesAllocations;

    private SystemStatus status;
    private Date nextOpeningDate;
    private int duration;
    private boolean allowSystemClosing;

    private boolean stopBidOnShareDepletion;
    private String domainUrl;
    private String filePaths;
    private String documentUploadDir;
    private boolean viewAvailableShares;

    private String phone;
    private String email;
	private boolean allowSystemNotifications;
	private boolean allowDefaultSms;
	private boolean sendMessageToclientOnRejection;
	private boolean approveAutoGeneratedBills;
	private String downloadPath;


}
