
bezkoder.app.jwtSecret=baksksksYAt5511514Ajsqeweweoqpq00922892
bezkoder.app.jwtExpirationMs=711200000


server.port=8083
server.servlet.context-path=/tezza
spring.datasource.url=jdbc:postgresql://localhost:5432/tezzaapp
spring.datasource.username=tezzauser
spring.datasource.password=tezza#$2026test
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


documentsUploadDir=/var/www/html/documents/uploads
filePath=http://localhost/documents/uploads/





spring.mvc.pathmatch.matching-strategy=ant_path_matcher
domain.url=http://84.8.129.26


scheduler.loan.process.delay=30000
scheduler.loan.pageSize=50
scheduler.loan.calculatorReturnsDelta=true


server.max-http-header-size=64KB


google.drive.credentials.file.path=~/driven-binder-491315-t8-ffb53bfdd5b3.json
google.drive.folder.name=DB_BACKUPS