package co.ke.tezza.loanapp.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;
import javax.persistence.*;

import org.hibernate.envers.Audited;

import co.ke.tezza.loanapp.enums.ReferralrewardTypeEnum;
import co.ke.tezza.loanapp.enums.SettingCategoriesEnum;
import co.ke.tezza.loanapp.enums.SystemStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "AD_Sys_Config")
@Audited
public class MADSysConfig extends AuditModel {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "AD_Sys_Config_ID")
	private long id;

	@Column(name = "isotp_allowed_onlogin", columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean oTPAllowedOnLogin;
	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean allowDefaultSms;

	@Column(name = "search_enabled", columnDefinition = "BOOLEAN DEFAULT TRUE")
	private boolean searchEnabled;

	@Enumerated(EnumType.STRING)
	@Column(name = "setting_category")
	private SettingCategoriesEnum settingCategory;

	@Column(name = "referral_benefits_enabled", columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean referralBenefitsEnabled;

	@Column(name = "referral_flat_bonus_amount")
	private java.math.BigDecimal referralFlatBonusAmount;
	@Column(name = "referral_flat_bonus_interest_rate")
	private java.math.BigDecimal referralFlatBonusInterestRate;

	@Enumerated(EnumType.STRING)
	@Column(name = "referral_reward_type")
	private ReferralrewardTypeEnum referralRewardType;

	@Column(name = "platform_name")
	private String platformName;

	private boolean referralBenefitIsOneTime;

	@Column(name = "platform_primary_color")
	private String platformPrimaryColor;
	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean allowSystemNotifications;
	
	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean accountingEnabled;

	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean sendMessageToclientOnRejection;
	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean approveAutoGeneratedBills;
	@Column( columnDefinition = "TEXT DEFAULT NULL")
	private String downloadPath;
	
	
	
	@Column( columnDefinition = "TEXT DEFAULT NULL")
	private String domainUrl;
	private String filePaths;
	private String documentUploadDir;
	
	
	private String phone;
	private String email;
	
	@Column( columnDefinition = "BOOLEAN DEFAULT FALSE")
	private boolean allowEmailNotifications;

	@Column(name = "ad_sys_config_UU")
	private String aD_Sys_Config_UU = UUID.randomUUID().toString();
}
